#!/usr/bin/env bash

echo "MISA         :" `grep '^0_' 1_MISA/assembly_0/ssrs.csv | wc -l`
echo "Primer3      :" `grep '^0_' 2_Primer3/assembly_0/primers.csv | wc -l` ", " `grep '^  [0-9]' 2_Primer3/assembly_0/primers.csv | wc -l`
echo "RepeatMasker :" `grep '^0_' 3_RepeatMasker/assembly_0/ssrs.csv | wc -l` ", " `grep '^  [0-9]' 3_RepeatMasker/assembly_0/ssrs.csv | wc -l`



for a_d in 5_amplify/assembly_*; do
    echo "" $a_d ":" `grep '^0_' $a_d/primers.csv | wc -l`
done

echo "Final        :" `grep '^0_' 6_final_primers.csv | wc -l`
